from __future__ import annotations

from datetime import timedelta, timezone
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

SCHEMA_VERSION = "2026-03-28.boardroom.v1"
try:
    BOARDROOM_TIMEZONE = ZoneInfo("Asia/Shanghai")
except ZoneInfoNotFoundError:
    BOARDROOM_TIMEZONE = timezone(timedelta(hours=8), name="Asia/Shanghai")

EVENT_SYSTEM_INITIALIZED = "SYSTEM_INITIALIZED"
EVENT_BOARD_DIRECTIVE_RECEIVED = "BOARD_DIRECTIVE_RECEIVED"
EVENT_WORKFLOW_CREATED = "WORKFLOW_CREATED"
EVENT_TICKET_CREATED = "TICKET_CREATED"
EVENT_TICKET_LEASED = "TICKET_LEASED"
EVENT_TICKET_STARTED = "TICKET_STARTED"
EVENT_TICKET_HEARTBEAT_RECORDED = "TICKET_HEARTBEAT_RECORDED"
EVENT_TICKET_CANCEL_REQUESTED = "TICKET_CANCEL_REQUESTED"
EVENT_TICKET_CANCELLED = "TICKET_CANCELLED"
EVENT_TICKET_COMPLETED = "TICKET_COMPLETED"
EVENT_TICKET_FAILED = "TICKET_FAILED"
EVENT_TICKET_TIMED_OUT = "TICKET_TIMED_OUT"
EVENT_TICKET_RETRY_SCHEDULED = "TICKET_RETRY_SCHEDULED"
EVENT_ARTIFACT_IMPORTED = "ARTIFACT_IMPORTED"
EVENT_ARTIFACT_DELETED = "ARTIFACT_DELETED"
EVENT_ARTIFACT_EXPIRED = "ARTIFACT_EXPIRED"
EVENT_ARTIFACT_CLEANUP_COMPLETED = "ARTIFACT_CLEANUP_COMPLETED"
EVENT_SCHEDULER_ORCHESTRATION_RECORDED = "SCHEDULER_ORCHESTRATION_RECORDED"
EVENT_INCIDENT_OPENED = "INCIDENT_OPENED"
EVENT_INCIDENT_RECOVERY_STARTED = "INCIDENT_RECOVERY_STARTED"
EVENT_INCIDENT_CLOSED = "INCIDENT_CLOSED"
EVENT_CIRCUIT_BREAKER_OPENED = "CIRCUIT_BREAKER_OPENED"
EVENT_CIRCUIT_BREAKER_CLOSED = "CIRCUIT_BREAKER_CLOSED"
EVENT_BOARD_REVIEW_REQUIRED = "BOARD_REVIEW_REQUIRED"
EVENT_BOARD_REVIEW_APPROVED = "BOARD_REVIEW_APPROVED"
EVENT_BOARD_REVIEW_REJECTED = "BOARD_REVIEW_REJECTED"
EVENT_MEETING_REQUESTED = "MEETING_REQUESTED"
EVENT_MEETING_STARTED = "MEETING_STARTED"
EVENT_MEETING_ROUND_COMPLETED = "MEETING_ROUND_COMPLETED"
EVENT_MEETING_CONCLUDED = "MEETING_CONCLUDED"
EVENT_EMPLOYEE_HIRED = "EMPLOYEE_HIRED"
EVENT_EMPLOYEE_REPLACED = "EMPLOYEE_REPLACED"
EVENT_EMPLOYEE_FROZEN = "EMPLOYEE_FROZEN"
EVENT_EMPLOYEE_RESTORED = "EMPLOYEE_RESTORED"

SYSTEM_INITIALIZED_KEY = "system:initialized"

APPROVAL_STATUS_OPEN = "OPEN"
APPROVAL_STATUS_APPROVED = "APPROVED"
APPROVAL_STATUS_REJECTED = "REJECTED"
APPROVAL_STATUS_MODIFIED_CONSTRAINTS = "MODIFIED_CONSTRAINTS"

TICKET_STATUS_PENDING = "PENDING"
TICKET_STATUS_LEASED = "LEASED"
TICKET_STATUS_EXECUTING = "EXECUTING"
TICKET_STATUS_CANCEL_REQUESTED = "CANCEL_REQUESTED"
TICKET_STATUS_CANCELLED = "CANCELLED"
TICKET_STATUS_COMPLETED = "COMPLETED"
TICKET_STATUS_FAILED = "FAILED"
TICKET_STATUS_TIMED_OUT = "TIMED_OUT"
TICKET_STATUS_BLOCKED_FOR_BOARD_REVIEW = "BLOCKED_FOR_BOARD_REVIEW"
TICKET_STATUS_REWORK_REQUIRED = "REWORK_REQUIRED"

NODE_STATUS_PENDING = "PENDING"
NODE_STATUS_EXECUTING = "EXECUTING"
NODE_STATUS_CANCEL_REQUESTED = "CANCEL_REQUESTED"
NODE_STATUS_CANCELLED = "CANCELLED"
NODE_STATUS_COMPLETED = "COMPLETED"
NODE_STATUS_BLOCKED_FOR_BOARD_REVIEW = "BLOCKED_FOR_BOARD_REVIEW"
NODE_STATUS_REWORK_REQUIRED = "REWORK_REQUIRED"

BLOCKING_REASON_BOARD_REVIEW_REQUIRED = "BOARD_REVIEW_REQUIRED"
BLOCKING_REASON_BOARD_REJECTED = "BOARD_REJECTED"
BLOCKING_REASON_MODIFY_CONSTRAINTS = "MODIFY_CONSTRAINTS"

DEFAULT_WORKFLOW_STAGE = "project_init"
DEFAULT_WORKFLOW_STATUS = "EXECUTING"
DEFAULT_BOARD_GATE_STATE = "UNREQUESTED"
DEFAULT_TENANT_ID = "tenant_default"
DEFAULT_WORKSPACE_ID = "ws_default"
DEFAULT_LEASE_TIMEOUT_SEC = 600
DEFAULT_REPEAT_FAILURE_THRESHOLD = 2
DEFAULT_TIMEOUT_REPEAT_THRESHOLD = 2
DEFAULT_TIMEOUT_BACKOFF_MULTIPLIER = 1.5
DEFAULT_TIMEOUT_BACKOFF_CAP_MULTIPLIER = 2.0
INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_RECOVERING = "RECOVERING"
INCIDENT_STATUS_CLOSED = "CLOSED"
CIRCUIT_BREAKER_STATE_OPEN = "OPEN"
CIRCUIT_BREAKER_STATE_CLOSED = "CLOSED"
INCIDENT_TYPE_REPEATED_FAILURE_ESCALATION = "REPEATED_FAILURE_ESCALATION"
INCIDENT_TYPE_RUNTIME_TIMEOUT_ESCALATION = "RUNTIME_TIMEOUT_ESCALATION"
INCIDENT_TYPE_PROVIDER_EXECUTION_PAUSED = "PROVIDER_EXECUTION_PAUSED"
INCIDENT_TYPE_MAKER_CHECKER_REWORK_ESCALATION = "MAKER_CHECKER_REWORK_ESCALATION"
INCIDENT_TYPE_STAFFING_CONTAINMENT = "STAFFING_CONTAINMENT"
INCIDENT_TYPE_REVIEW_GATE_MERGE_FAILED = "REVIEW_GATE_MERGE_FAILED"
TIMEOUT_FAMILY_RUNTIME = "runtime-timeout"
PROVIDER_FINGERPRINT_PREFIX = "provider"
FAILURE_KIND_PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
FAILURE_KIND_UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
FAILURE_KIND_FIRST_TOKEN_TIMEOUT = "FIRST_TOKEN_TIMEOUT"
FAILURE_KIND_STREAM_IDLE_TIMEOUT = "STREAM_IDLE_TIMEOUT"
PROVIDER_PAUSE_FAILURE_KINDS = {
    FAILURE_KIND_PROVIDER_RATE_LIMITED,
    FAILURE_KIND_UPSTREAM_UNAVAILABLE,
    FAILURE_KIND_FIRST_TOKEN_TIMEOUT,
    FAILURE_KIND_STREAM_IDLE_TIMEOUT,
}

EMPLOYEE_STATE_ACTIVE = "ACTIVE"
EMPLOYEE_STATE_FROZEN = "FROZEN"
EMPLOYEE_STATE_REPLACED = "REPLACED"

STREAM_TYPE = "boardroom_events"
