from __future__ import annotations

from datetime import timedelta, timezone
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

SCHEMA_VERSION = "2026-03-28.boardroom.v1"
try:
    BOARDROOM_TIMEZONE = ZoneInfo("Asia/Shanghai")
except ZoneInfoNotFoundError:
    BOARDROOM_TIMEZONE = timezone(timedelta(hours=8), name="Asia/Shanghai")

EVENT_SYSTEM_INITIALIZED = "SYSTEM_INITIALIZED"
EVENT_BOARD_DIRECTIVE_RECEIVED = "BOARD_DIRECTIVE_RECEIVED"
EVENT_WORKFLOW_CREATED = "WORKFLOW_CREATED"
EVENT_TICKET_CREATED = "TICKET_CREATED"
EVENT_TICKET_LEASED = "TICKET_LEASED"
EVENT_TICKET_STARTED = "TICKET_STARTED"
EVENT_TICKET_COMPLETED = "TICKET_COMPLETED"
EVENT_TICKET_FAILED = "TICKET_FAILED"
EVENT_TICKET_TIMED_OUT = "TICKET_TIMED_OUT"
EVENT_TICKET_RETRY_SCHEDULED = "TICKET_RETRY_SCHEDULED"
EVENT_BOARD_REVIEW_REQUIRED = "BOARD_REVIEW_REQUIRED"
EVENT_BOARD_REVIEW_APPROVED = "BOARD_REVIEW_APPROVED"
EVENT_BOARD_REVIEW_REJECTED = "BOARD_REVIEW_REJECTED"

SYSTEM_INITIALIZED_KEY = "system:initialized"

APPROVAL_STATUS_OPEN = "OPEN"
APPROVAL_STATUS_APPROVED = "APPROVED"
APPROVAL_STATUS_REJECTED = "REJECTED"
APPROVAL_STATUS_MODIFIED_CONSTRAINTS = "MODIFIED_CONSTRAINTS"

TICKET_STATUS_PENDING = "PENDING"
TICKET_STATUS_LEASED = "LEASED"
TICKET_STATUS_EXECUTING = "EXECUTING"
TICKET_STATUS_COMPLETED = "COMPLETED"
TICKET_STATUS_FAILED = "FAILED"
TICKET_STATUS_TIMED_OUT = "TIMED_OUT"
TICKET_STATUS_BLOCKED_FOR_BOARD_REVIEW = "BLOCKED_FOR_BOARD_REVIEW"
TICKET_STATUS_REWORK_REQUIRED = "REWORK_REQUIRED"

NODE_STATUS_PENDING = "PENDING"
NODE_STATUS_EXECUTING = "EXECUTING"
NODE_STATUS_COMPLETED = "COMPLETED"
NODE_STATUS_BLOCKED_FOR_BOARD_REVIEW = "BLOCKED_FOR_BOARD_REVIEW"
NODE_STATUS_REWORK_REQUIRED = "REWORK_REQUIRED"

BLOCKING_REASON_BOARD_REVIEW_REQUIRED = "BOARD_REVIEW_REQUIRED"
BLOCKING_REASON_BOARD_REJECTED = "BOARD_REJECTED"
BLOCKING_REASON_MODIFY_CONSTRAINTS = "MODIFY_CONSTRAINTS"

DEFAULT_WORKFLOW_STAGE = "project_init"
DEFAULT_WORKFLOW_STATUS = "EXECUTING"
DEFAULT_BOARD_GATE_STATE = "UNREQUESTED"
DEFAULT_LEASE_TIMEOUT_SEC = 600

STREAM_TYPE = "boardroom_events"
